### ISSUE TITLE
Problem with the preconfigured environment variable `RUN_BULLMQ_WORKERS`

### ISSUE THREAD

**Issue by thomassuedbroecker** [i-am-bee/bee-api#140]
FYI @Tomas2D 

### Problem

I had a problem when I started the API. I get the following problem.

```sh
Error: Unknown items runs:cleanup,vectorStores:cleanup,vectorStores:fileProcessor,files:extraction:node,files:extraction:python,threads:cleanup,files:cleanup in RUN_BULLMQ_WORKERS
    at getStringArray (/Users/thomassuedbroecker/Documents/tsuedbro/dev/bee-api/src/config.ts:50:35)
    at <anonymous> (/Users/thomassuedbroecker/Documents/tsuedbro/dev/bee-api/src/config.ts:172:35)
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
```

### Verification

I verified what is expected in ```src/config.ts```

```sh
INFO current values:
runs,runs:cleanup,vectorStores:cleanup,vectorStores:fileProcessor,files:extraction:node,files:extraction:python,threads:cleanup,files:cleanup
INFO allowed values:
runs,runs-cleanup,threads-cleanup,vectorStores-cleanup,vectorStores-fileProcessor,files-extraction-node,files-extraction-python,files-cleanup
```

I noticed that the `RUN_BULLMQ_WORKERS` variable need to be changed in the `.env` file.

```sh
# Queue workers
RUN_BULLMQ_WORKERS=runs,runs:cleanup,vectorStores:cleanup,vectorStores:fileProcessor,files:extraction:node,files:extraction:python,threads:cleanup,files:cleanup
```

### Solution

After I changed the entry in the .env, it worked again.

```sh
# Queue workers
RUN_BULLMQ_WORKERS=runs,runs-cleanup,threads-cleanup,vectorStores-cleanup,vectorStores-fileProcessor,files-extraction-node,files-extraction-python,files-cleanup
```

**Comment by xjacka** [comment]
Yes, this is breaking change, worker names must be changed. See env.example: https://github.com/i-am-bee/bee-api/blob/main/.env.example#L42

**Comment by thomassuedbroecker** [comment]
Thanks, strange, I did an update of my fork in synchronized it but the example environment file was not updated.
