### ISSUE TITLE
Error when running local Ollama model 3.1: model 'meta-llama/llama-3-1-70b-instruct' not found

### ISSUE THREAD

**Issue by MuhammadKurdi-CS** [i-am-bee/bee-api#99]
Hi, I'm encountering an issue while running the UI and API locally for development, I'm also using the Bee stack as instructed. When attempting to use the Ollama model, the following error occurs:

```
[16:06:08.309] ERROR (bee-api): Job failed {"queueName":"runs","job":{"id":"run_674894f03fdbfc1891592a36","name":"runs","failedReason":"model 'meta-llama/llama-3-1-70b-instruct' not found","data":{"runId":"run_674894f03fdbfc1891592a36"}}}
    err: {
      "type": "ResponseError",
      "message": "model 'meta-llama/llama-3-1-70b-instruct' not found",
      "stack":
          ResponseError: model 'meta-llama/llama-3-1-70b-instruct' not found
              at checkOk (file:///Users/muhammadmohammadi/Documents/llm_Agentic_Data_Interaction/project/bee/bee-ui-api/bee-api/node_modules/.pnpm/ollama@0.5.9/node_modules/ollama/dist/shared/ollama.133b951a.mjs:70:9)
              at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
              at async post (file:///Users/muhammadmohammadi/Documents/llm_Agentic_Data_Interaction/project/bee/bee-ui-api/bee-api/node_modules/.pnpm/ollama@0.5.9/node_modules/ollama/dist/shared/ollama.133b951a.mjs:118:3)
              at async Ollama.show (file:///Users/muhammadmohammadi/Documents/llm_Agentic_Data_Interaction/project/bee/bee-ui-api/bee-api/node_modules/.pnpm/ollama@0.5.9/node_modules/ollama/dist/shared/ollama.133b951a.mjs:383:22)
              at async OllamaChatLLM.meta (/Users/muhammadmohammadi/Documents/llm_Agentic_Data_Interaction/project/bee/bee-ui-api/bee-api/node_modules/.pnpm/bee-agent-framework@0.0.42_@bufbuild+protobuf@1.10.0_@googleapis+customsearch@3.2.0_@grpc+grp_6ksezj3j3d6gaziesabjtuvxii/node_modules/bee-agent-framework/src/adapters/ollama/chat.ts:148:19)
              at async TokenMemory.add (/Users/muhammadmohammadi/Documents/llm_Agentic_Data_Interaction/project/bee/bee-ui-api/bee-api/node_modules/.pnpm/bee-agent-framework@0.0.42_@bufbuild+protobuf@1.10.0_@googleapis+customsearch@3.2.0_@grpc+grp_6ksezj3j3d6gaziesabjtuvxii/node_modules/bee-agent-framework/src/memory/tokenMemory.ts:85:20)
              at async TokenMemory.addMany (/Users/muhammadmohammadi/Documents/llm_Agentic_Data_Interaction/project/bee/bee-ui-api/bee-api/node_modules/.pnpm/bee-agent-framework@0.0.42_@bufbuild+protobuf@1.10.0_@googleapis+customsearch@3.2.0_@grpc+grp_6ksezj3j3d6gaziesabjtuvxii/node_modules/bee-agent-framework/src/memory/base.ts:43:7)
              at async executeRun (/Users/muhammadmohammadi/Documents/llm_Agentic_Data_Interaction/project/bee/bee-ui-api/bee-api/src/runs/execution/execute.ts:132:3)
              at async <anonymous> (/Users/muhammadmohammadi/Documents/llm_Agentic_Data_Interaction/project/bee/bee-ui-api/bee-api/src/runs/jobs/runs.queue.ts:75:7)
              at async Worker.processJob (/Users/muhammadmohammadi/Documents/llm_Agentic_Data_Interaction/project/bee/bee-ui-api/bee-api/node_modules/.pnpm/bullmq@5.8.1/node_modules/bullmq/src/classes/worker.ts:786:22)
      "error": "model 'meta-llama/llama-3-1-70b-instruct' not found",
      "status_code": 404,
      "name": "ResponseError"
    }
```

**Comment by pilartomas** [comment]
Hello, it appears that you're using Ollama backend but using model id belonging to another backend. Most likely you have switched backends but kept your database intact.

Possible remedies:
- create a new bee assistant in the UI, that one should have proper model id
- wipe your bee-stack volumes (mongodb database specifically), that will rerun the seeded and seed proper model id of the default bee assistant

**Comment by MuhammadKurdi-CS** [comment]
thank you, those steps helped me resolve my issue.
